apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-pipeline

resources:
  - namespace.yaml
  - secrets.yaml
  - pvc.yaml
  - rbac.yaml
  - postgres-source-configmap.yaml
  - postgres-target-configmap.yaml
  - postgres-source-deployment.yaml
  - postgres-target-deployment.yaml
  - airflow-deployment.yaml
