apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ecommerce-pipeline
type: Opaque
stringData:
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-db
  namespace: ecommerce-pipeline
type: Opaque
stringData:
  connection-string: postgresql://airflow:airflow@postgres-source:5432/airflow
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet
  namespace: ecommerce-pipeline
type: Opaque
stringData:
  key: "7T0DZ75Yy0OsDFQVIkOBDXiLlO_AZccuMJRQosCT2I0="
